apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" 