apiVersion: v1
kind: Pod
metadata:
  name: app-pv-pod2
spec:
  volumes:
    - name: app-pv-storage
      persistentVolumeClaim:
        claimName: app-volume-claim
  containers:
    - name: app-pv-container
      image: httpd
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/"
          name: app-pv-storage