apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc #replication controlller
spec:
  replicas: 3
  selector: # Label Selector (Look after the pods that have the following lables)
    app: nginx
  template: #pod template
    metadata:
      name: nginx
      labels:
        app: nginx
        
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80